---
version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  commit-message:
    prefix: ci(deps)
- package-ecosystem: terraform
  directory: /
  schedule:
    interval: monthly
  commit-message:
    prefix: chore(deps)
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-major
