name: terraform
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: 1
      TF_INPUT: 0
    steps:
    - uses: actions/checkout@master
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.4
    - run: terraform fmt -check -recursive
